### ISSUE TITLE
Clarification on Running All Three Types of Data-Free Extraction Attacks

### ISSUE THREAD

**Issue by 1171000712** [joey-wang123/DFME-DRO#1]
Hi,

Thank you for sharing your code and for the great work in your paper! I’m interested in replicating the experiments you conducted against the three types of data-free extraction attacks mentioned in your paper.

However, I noticed that the provided code only includes one command and there aren’t clear options in the arguments for running the different types of attacks. Could you please provide guidance or example commands on how to execute all three types of extraction attacks as presented in the paper?

Your help would be greatly appreciated!

**Comment by joey-wang123** [comment]
Thank you for your interest! 

For the first step:

The defensive training against three types of attacks is similar. 

"python teacher-train_DRO.py --dataset cifar10 --model resnet34_8x  --method SVGD."  In this command, the argument "dataset" indicates the defensive training is performed on cifar10 dataset. you can change the dataset to be cifar100 to perform defensive training on cifar100.  The argument "model" indicates the victim model is resnet34_8x. The argument "method" indicates the solver for DRO is SVGD.

For the second step:

This is to perform the model extraction with the defense of MeCo.

"python3 train_cifar10.py --model resnet34_8x --dataset cifar10 --scale 0.27 --batch_size 64 --ckpt 'path/to/your/DROmodel'    --device 0 --grad_m 1 --query_budget 20 --log_dir 'path/to/your/log/dir'  --lr_G 1e-4 --student_model resnet18_8x --loss l1;"     In this command, this is to evaluate the defense performance with the DFME attack [1].   The argument "model" is the victim model architecture. The argument "dataset" indicates that the victim model is trained on cifar10. The argument "scale" is to set the input perturbation scale.  The argument "batch size" is to set the batch size used by the attacker to extract the victim model.   The argument  "ckpt" is the victim model obtained in the first step by defensive training. The argument "device" indicates that the model uses the first GPU.  The argument "query_budget" indicates the query budget is set to be 20 million data points. The argument "student_model" is used for setting the clone model architecture, you can set it to be other architectures. The argument "loss" is used for setting the extraction loss to be "l1" loss for the attacker.  

Similarly, if performing MAZE attack [2]. The command is 

 python3 train_cifar10.py --MAZE --model resnet34_8x --dataset cifar10 --scale 0.27 --batch_size 64 --ckpt 'path/to/your/DROmodel'    --device 0 --grad_m 1 --query_budget 20 --log_dir 'path/to/your/log/dir'  --lr_G 1e-4 --student_model resnet18_8x;  

For the third type of attack [3], since cleaning the code base of [3] a bit more complicated, the cleaning is not finished. I will release the code when finished. 

Let me know if you need more explanations. Thanks again for your interest!
 

Reference:

[1] Data-Free Model Extraction, CVPR 2021. 
[2] MAZE: Data-Free Model Stealing Attack Using Zeroth-Order Gradient Estimation, CVPR 2021.
[3] Towards Data-Free Model Stealing in a Hard Label Setting, CVPR 2022.

**Comment by 1171000712** [comment]
Thank you very much for your quick and detailed reply. My confusion was completely solved.

**Comment by joey-wang123** [comment]
You are welcome.

**Comment by 1439238771** [comment]
Hello, I have a question about the relationship between the perturbation model used in defense during the model stealing process and the perturbation model used in the defense phase. I noticed that the perturbation model used during the stealing process seems to be obtained by resetting parameters. Additionally, we found that the mean L2 value of perturbations obtained on OOD (Out-of-Distribution) data is much smaller compared to the mean IND (In-Distribution) perturbation. Is this normal?
